name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # දිනපතා අප්ඩේට් වේ
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ChamathSadaru
          template: classic
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          output_action: commit
          committer_branch: output # මෙතැන 'output' ලෙස දීමෙන් ඔයාගේ ලින්ක් එක වැඩ කරනු ඇත
          filename: isocalendar.svg
